### ISSUE TITLE
waittime behavior

### ISSUE THREAD

**Issue by toddjames** [thombashi/pingparsing#21]
Thanks for all of the effort you've put into this library. It's the only one that I've found to be actively developed and work well.

There is a bug with respect to either the logic or exception message for waittime in the PingTransmitter class:

```
       if self.waittime <= 0:
            raise ValueError(
                "wait time must be greater than or equal to zero")
```

When `waittime` is set to `0`, the exception is raised, which states that the 

> wait time must be greater than or equal to zero

According to the exception, `0` should be a valid value, but it isn't

More to the point, what prompted me to start digging into this is that I was looking for a way to exclude the use of the `-w` flag on Linux altogether. I want ping to return as soon as it's done.

As a feature request in addition to the bug above, it would be very helpful to be able to set waittime to `0` and have the `-w` flag not be passed to ping.

**Comment by thombashi** [comment]
Thank you for the report.

You are correct.

>wait time must be greater than or equal to zero

This error message is incorrect, correctly it should be 

```
wait time must be greater than zero
```

I've fixed the error message.

>As a feature request in addition to the bug above, it would be very helpful to be able to set waittime to 0 and have the -w flag not be passed to ping.

And I add capability to ignore waittime by setting `None` with `pingparsing` 0.4.0.

**Comment by toddjames** [comment]
Works perfectly, thanks!
