### ISSUE TITLE
Add "count" property

### ISSUE THREAD

**Issue by toddjames** [thombashi/pingparsing#22]
Would it be possible to add a `count` property to the PingTransmitter class, which sets the `-c <count>` flag on Linux and the `-n <count>` flag on Windows?

I'm currently using the `ping_option` property, which works well enough, but this would be a nice option.

**Comment by thombashi** [comment]
Thank you for your suggestion.

I agree with you, count option would one of the frequently used option.
I've added `count` property to PingTransmitter class with `pingparsing` 0.4.0.

**Comment by toddjames** [comment]
Works perfectly, thanks!
