### ISSUE TITLE
All rtt data: None

### ISSUE THREAD

**Issue by maikotz** [thombashi/pingparsing#27]
Hi,

I'm getting always None from pingparsing when processing results.

```
DEBUG result:PingResult(stdout='PING heise.de (193.99.144.80): 56 data bytes\n\n--- heise.de ping statistics ---\n5 packets transmitted, 5 packets received, 0% packet loss\nround-trip min/avg/max = 0.638/0.683/0.746 ms\n', stderr='', returncode=0)
DEBUG parser:{'rtt_min': None, 'packet_duplicate_count': None, 'packet_loss_count': 0, 'rtt_max': None, 'packet_loss_rate': 0.0, 'packet_receive': 5, 'rtt_mdev': None, 'packet_transmit': 5, 'packet_duplicate_rate': None, 'rtt_avg': None}
```

Any idea what's wrong? The output is generated from alpine linux in a docker container.

**Comment by thombashi** [comment]
Thank you for your report.

The reason why RTT values always `None` was that ABDE not supported Alpine Linux ping format.
I have updated `pingparsing` to support Alpine Linux ping format at `0.10.0`.
Please try this version.

**Comment by thombashi** [comment]
@maikotz
I'll close the issue.
Feel free to reopen if you have any problems with Alpine Linux environment.

**Comment by maikotz** [comment]
sorry for the late reply! 

Everything is working with 0.10.0.

Cheers!
