### ISSUE TITLE
AttributeError on transmit failure

### ISSUE THREAD

**Issue by psmorris** [thombashi/pingparsing#33]
Hi, 

I'm running pingparsing on a raspberry pi on a cron to verify that my home network is connected to the internet. When the connection is up, it works great. When the connection goes down, I'm receiving the following error:

    ping_dict = ping_parser.parse(result).as_dict()
  File "/home/pi/.local/lib/python2.7/site-packages/pingparsing/_pingparsing.py", line 141, in parse
    ping_lines = _to_unicode(ping_message).splitlines()
AttributeError: 'PingResult' object has no attribute 'splitlines'

Here is my source code:
ping_parser = pingparsing.PingParsing()
transmitter = pingparsing.PingTransmitter()
transmitter.destination = ping_host
transmitter.count = 10
result = transmitter.ping()
ping_dict = ping_parser.parse(result).as_dict()

**Comment by thombashi** [comment]
Thank you for your report.

I had fixed the problem at `pingparsing 0.18.2`.
Please try that version.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
