### ISSUE TITLE
Support for packet size (-s option)

### ISSUE THREAD

**Issue by salehdeh76** [thombashi/pingparsing#34]
can you please add support for setting packet size?
Also it is so fine to support (-t TTL) option

**Comment by thombashi** [comment]
@salehdeh76 
Thank you for your feedback.

I will consider the feature for future releases.
For a temporary workaround, you can pass options to ping via [ping_option]( https://pingparsing.readthedocs.io/en/latest/pages/reference/transmitter.html#pingparsing.PingTransmitter.ping_option ) property.

**Comment by thombashi** [comment]
I had added packet size and ttl support at `pingparsing 1.0.0`
