### ISSUE TITLE
Doc comment for PingTransmitter.deadline is missing one line

### ISSUE THREAD

**Issue by oliver** [thombashi/pingparsing#39]
In the doc comment for `PingTransmitter.deadline` attribute, the third line apparently lacks the correct ending. At https://github.com/thombashi/pingparsing/blob/master/pingparsing/_pingtransmitter.py#L176 the comment currently looks like this:

```
        If both :py:attr:`~.deadline` and :py:attr:`~.count` are |None|,
        If only a number is specified and a unit not found, the unit will be considered as seconds.
```

I think the end of the sentence "```If both :py:attr:`~.deadline` and :py:attr:`~.count` are |None|,```" got lost in commit https://github.com/thombashi/pingparsing/commit/f38da4d1de677079306d08a1c26a410fab9e3cfa?

**Comment by thombashi** [comment]
Thank you for your feedback.

I had fixed the docstring.
